apiVersion : v1 
kind : ConfigMap
metadata : 
  name : userd-db-config
data : 
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_DB: usersdb
---
apiVersion : v1 
kind : ConfigMap
metadata : 
  name : booksdb-config
data : 
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_DB: usersdb
